updated: app's documentation
vtex-apps/quantity-on-cart pull request #5
Opened 2022-04-08 17:32 UTC by Mariana-Caetano

The purpose of this PR is to update the `README.md` according to the Education team guidelines.

2022-04-08 17:35 UTC, Mariana-Caetano commented on README.md
> +> The Quantity On Cart app does not work with promotions that split products.
@ahermelo or @germanBonacchi I'm not sure if I understand this warning. What does it mean **promotions that split products**? And why the app does not work with them?

2022-04-18 17:53 UTC, germanBonacchi commented on README.md
> +> The Quantity On Cart app does not work with promotions that split products.
Hi, some promotions like 2x1 or 3x2, when you add products that not complete the promotions, make in the same orderForm 2 products with the same id and the app is finding the id, so will get the first product with the id that have only have 2 and the next product have 1.

That the reason of the warning.

2022-04-18 20:27 UTC, Mariana-Caetano commented on README.md
> +> The Quantity On Cart app does not work with promotions that split products.
Thanks, @germanBonacchi! Can you give your review for the PR? Then we can merge and make the doc available. Thanks!

2022-04-22 17:34 UTC, julia-rabello commented on README.md
> +The **Quantity On Cart app** displays a message informing customers of the quantity of the same product they have added to the cart.
Aqui acho que ficaria mais direto mudando para algo como:

> The Quantity on Cart app allows you to display a message to your customers informing how many units of a product they have added to the cart.

Outro ponto: onde essa mensagem pode ser exibida? Só na product shelf na home? Ou poderia estar na página de detalhes do produto também, por exemplo? Acho que vale incluir essa informação.

2022-04-22 17:43 UTC, julia-rabello commented on README.md
> +4. Add the `quantity-on-cart` block to other theme block using a product context since the `quantity-on-cart` block handles product data. For example, the [`product-summary.shelf`](https://developers
Aqui acho que vale dizer quais blocos aceitam o quantity-on-cart, se tiver essa informação

2022-04-22 17:48 UTC, julia-rabello commented on README.md
> +> The Quantity On Cart app does not work with promotions scenarios such as [Buy Together](https://help.vtex.com/en/tutorial/buy-together--tutorials_323) and [Buy One Get One](https://help.vtex.com/en
```suggestion
> ⚠️ The Quantity On Cart app does not work with promotions scenarios such as [Buy Together](https://help.vtex.com/en/tutorial/buy-together--tutorials_323) and [Buy One Get One](https://help.vtex.com/en/tutorial/buy-one-get-one--tutorials_322).
```

2022-04-22 17:52 UTC, julia-rabello commented on README.md
> +> The displayed message in the Quantity On Cart app is available in three languages: English, Spanish, and Portuguese, and follows the pattern below, which cannot be changed: `You have x units in you
```suggestion
> ℹ️ The displayed message in the Quantity On Cart app is available in three languages: English, Spanish, and Portuguese, and follows the pattern below, which cannot be changed: `You have x units in your shopping cart.`
```

2022-04-22 17:53 UTC, julia-rabello commented on README.md
> +> The displayed message in the Quantity On Cart app is available in three languages: English, Spanish, and Portuguese, and follows the pattern below, which cannot be changed: `You have x units in you
Talvez seja interessante incluir como fica a mensagem nos outros idiomas, já que só tem esses três e não dá para alterar.

2022-04-22 17:57 UTC, julia-rabello requested changes
@Mariana-Caetano achei muito bom! Só deixei algumas sugestões. Também percebi que faltou adicionar o [docs builder](https://github.com/vtex-apps/io-documentation) e criar a pasta `docs` para armazenar o `README.md`.

2022-04-22 21:37 UTC, merged